### ISSUE TITLE
Night light does not work in GNOME Wayland (missing GAMMA_LUT support)

### ISSUE THREAD

**Issue by Gert-dev** [NVIDIA/open-gpu-kernel-modules#162]
**NVIDIA Driver Version**
515.43.04

**GPU**
NVIDIA RTX 2070 Super Max-Q

**Describe the bug**
Enabling night light in GNOME has no effect.

This bug also exists with the proprietary driver, but also seems to exist with the new, open, driver (hence this report).

**To Reproduce**
1. Enable night light in GNOME 42.1 on Wayland.
2. Set the time so that it is currently active.
3. Set the intensity high enough to be noticeable (warm).
4. Observe nothing happening.

**Expected behavior**
The night light works as intended by making the colours of the screen warmer.

**Please reproduce the problem, run nvidia-bug-report.sh, and attach the resulting nvidia-bug-report.log.gz.**

[nvidia-bug-report.log.gz](https://github.com/NVIDIA/open-gpu-kernel-modules/files/8690924/nvidia-bug-report.log.gz)

**Comment by ValZapod** [comment]
Why would they implement it when little cms is so much better? Also since when do you need a LUT to do global dimming???

**Comment by Newbytee** [comment]
Upstream bug report: https://gitlab.gnome.org/GNOME/mutter/-/issues/290

**Comment by quaqadm** [comment]
i am with same problem.

**Comment by santhosh-reddy03** [comment]
Hi Team,
I am facing this issue on x11 as well, when i click on the night light and move the slider, it turns on for a movement and exits from there, there after.
Nvidia Driver Version: 515.65.01
Please look into this issue at the earliest possible time.

**Comment by pyt0xic** [comment]
Not sure if it helps but Gammastep works flawlessly for me with wlroots compositors.
Maybe worth a look...

**Comment by MahouShoujoMivutilde** [comment]
@pyt0xic could you tell me more about your system?

I am on 520.56.06 _proprietary_ driver (pre-turing gpu), but I would expect that `gammastep` would either work on both or fail on both since "This code base is shared with NVIDIA's proprietary drivers" (from readme).

Hyprland compositor.

Launching `gammastep -m wayland -PO 2600` gives

```
Warning: Zero outputs support gamma adjustment.
Warning: 1/1 output(s) do not support gamma adjustment.
```

What compositor do you use?

**Comment by pyt0xic** [comment]
I was using Sway and am now running Hyprland.
I have an Optimus laptop but usually force dGPU.

I'll add more once I'm back from work.
But maybe double check all your Wayland related env vars.

**Comment by yannjor** [comment]
> I was using Sway and am now running Hyprland. I have an Optimus laptop but usually force dGPU.
> 
> I'll add more once I'm back from work. But maybe double check all your Wayland related env vars.

Could you please share your env vars?

**Comment by LukasF1337** [comment]
It is a known missing feature that GAMMA_LUT is not implemented in nvidias wayland driver yet:
http://us.download.nvidia.com/XFree86/Linux-x86_64/525.89.02/README/wayland-issues.html
which will be implemented at some point in the future according to their site.
@santhosh-reddy03 on my system setting the gamma LUT on X11 in KDE Plasma works.

**Comment by santhosh-reddy03** [comment]
Actually somehack from ubuntu launchpad bugs helped me fix the issue, i don't remember the variable name but on setting it to false, everything worked as usual, and glad to know nvidia is on it , hope to see in some time in future.

**Comment by rwjack** [comment]
@santhosh-reddy03 well which variable was it?

**Comment by santhosh-reddy03** [comment]
@rwjack there were two issues, the pc was also not waking up from sleep, i am think its Ubuntu 22.04 specific issue in my case, i m attaching the [bug link](https://bugs.launchpad.net/mutter/+bug/1968040) here, it has worked for me at that time, since then i switched back to x11.

**Comment by rwjack** [comment]
Yeah I'm switching back to x11 until I get a new GPU.

**Comment by MahouShoujoMivutilde** [comment]
I am not using gnome, but if there is some software that lets you draw your own custom shader as an overlay for the whole screen - you can make your own night light.

In hyprland there is an option for that

```
# hyprland.conf

decoration {
    screen_shader = ~/.config/hypr/your-shader.glsl
}

```

Here is the shader I use

https://github.com/hyprwm/Hyprland/issues/1140#issuecomment-1335128437

<details>
  <summary>Result: </summary>

No shader:

![01-03-2023-02_00_41](https://user-images.githubusercontent.com/14999778/222002059-46f14077-f164-4793-b4e9-de839ab7b234.jpg)

Shader:

![01-03-2023-02_00_47](https://user-images.githubusercontent.com/14999778/222002029-a38e4ea8-70d8-426d-8778-44ee8f298dbf.jpg)

</details>

It is trivial to automate it to apply on sunset.

Idk if gnome can do custom shaders, maybe ask the devs nicely to make a fallback implementation for nightlight if nvidia gpu is detected, because it doesn't seem like GAMMA_LUT will happen on nvidia any time soon.

**Comment by eszlari** [comment]
One year ago a Nvidia dev wrote:

> Support for GAMMA_LUT is in the queue, but no ETA at the moment.

https://github.com/Plagman/gamescope/pull/454#issuecomment-1076680841

**Comment by eszlari** [comment]
https://forums.developer.nvidia.com/t/nvidia-bug-kde-wayland-games-are-force-vsynced/237880/3

> Work on Gamma LUT support is also in progress. The implementation is currently under internal code-review.

**Comment by rwjack** [comment]
Yeah, that quote is from the 28th of December 2022.

**Comment by aviallon** [comment]
@rwjack Finally!

> The vsync issue will be fixed in the 545 driver release. Unfortunately I wasn’t able to get it in in time for the 535 release which will go public in a few days, sorry. But 545 will be the next release after that (we’re skipping 540 for whatever reason).



https://forums.developer.nvidia.com/t/nvidia-bug-kde-wayland-games-are-force-vsynced/237880/21

**Comment by Newbytee** [comment]
> @rwjack Finally!
> 
> > The vsync issue will be fixed in the 545 driver release. Unfortunately I wasn’t able to get it in in time for the 535 release which will go public in a few days, sorry. But 545 will be the next release after that (we’re skipping 540 for whatever reason).
> 
> https://forums.developer.nvidia.com/t/nvidia-bug-kde-wayland-games-are-force-vsynced/237880/21

How is this related to night light/GAMMA_LUT?

**Comment by rwjack** [comment]
> How is this related to night light/GAMMA_LUT?

Just Nvidia smokescreen trying to keep us onboard :joy:

**Comment by aviallon** [comment]
> > @rwjack Finally!
> > > The vsync issue will be fixed in the 545 driver release. Unfortunately I wasn’t able to get it in in time for the 535 release which will go public in a few days, sorry. But 545 will be the next release after that (we’re skipping 540 for whatever reason).
> > 
> > 
> > https://forums.developer.nvidia.com/t/nvidia-bug-kde-wayland-games-are-force-vsynced/237880/21
> 
> How is this related to night light/GAMMA_LUT?

Sadly, the two subjects were discussed at the same time in the same thread.
And I misread 😢

**Comment by eszlari** [comment]
Plasma 6 will support night color on Nvidia without GAMMA_LUT:

https://invent.kde.org/plasma/kwin/-/merge_requests/4130

**Comment by zer0-x** [comment]
> Plasma 6 will support night color on Nvidia without GAMMA_LUT:
> 
> https://invent.kde.org/plasma/kwin/-/merge_requests/4130

It uses a shader based fallback. It's just a work around, not an actual support.

It is not efficient and I think that colours will be also different when capturing the screen, since it's not a GPU side based solution (didn't test it, I'm not sure).

**Comment by Sohail-XD** [comment]
@MahouShoujoMivutilde this worked thanks, btw can I get dots for the bar in your picture?

**Comment by MahouShoujoMivutilde** [comment]
@Sohail-XD The bar evolved since then, here is how the current one looks:

<details>
  <summary> Waybar</summary>

![05-07-2023-23_33_54](https://github.com/NVIDIA/open-gpu-kernel-modules/assets/14999778/969882bf-8621-470d-87f3-d0a181d491e5)


</details>

configs:

<details>
  <summary> waybar/config </summary>

```jsonc

// vim: set ft=jsonc:
{
    "layer": "top",
    "position": "top", // Waybar position (top|bottom|left|right)
    "height": 30, // Waybar height (to be removed for auto height)
    // "width": 1280, // Waybar width
    "spacing": 0, // Gaps between modules (set in style.css for mor precision)
    "modules-left": [
        "cpu",
        "wlr/workspaces"
    ],
    "modules-center": [
        "hyprland/window"
    ],
    "modules-right": [
        "custom/isrecording",
        "custom/nvtemp",
        "custom/cputemp",
        "custom/memory",
        "idle_inhibitor",
        "pulseaudio",
        "bluetooth",
        "hyprland/language",
        "custom/sunset",
        "clock",
        "tray",
        "custom/notification"
    ],
    "idle_inhibitor": {
        "format": "{icon}",
        "format-icons": {
            "activated": "",
            "deactivated": ""
        }
    },
    "cpu": {
        "interval": 1,
        // cores including HT
        "format": "{icon0} {icon1} {icon2} {icon3} {icon4} {icon5} {icon6} {icon7} {icon8} {icon9} {icon10} {icon11} {icon12} {icon13} {icon14} {icon15}",
        "format-icons": [ "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█" ],
    },
    "custom/isrecording": {
        "exec": "isrecording",
        "interval": 1
    },
    "custom/memory": {
        "exec": "~/.config/waybar/scripts/waybar-mem",
        "interval": 1
    },
    "custom/nvtemp": {
        "format": "3D {} °C",
        "exec": "nvtemp 65",
        "interval": 2
    },
    "custom/cputemp": {
        "format": "CPU {} °C",
        "exec": "cputemp 60",
        "interval": 2
    },
    "wlr/workspaces": {
        "format": "{name}",
        "on-click": "activate",
        "sort-by-number": true
    },
    "bluetooth": {
        "format": " {status}",
        "format-on": "",
        "format-off": "",
        "format-disabled": "",
        "format-connected": " {device_alias}",
        "format-connected-battery": "{device_battery_percentage}%  ",
        "tooltip-format": "{controller_alias}\t{controller_address}\n\n{num_connections} connected",
        "tooltip-format-connected": "{controller_alias}\t{controller_address}\n\n{num_connections} connected\n\n{device_enumerate}",
        "tooltip-format-enumerate-connected": "{device_alias}\t{device_address}",
        "tooltip-format-enumerate-connected-battery": "{device_alias}\t{device_address}\t{device_battery_percentage}%"
    },
    "hyprland/language": {
        "format": " {}",
        "format-en": "us",
        "format-ru": "ru",
        "keyboard-name": "logitech-usb-keyboard"
    },
    "hyprland/window": {
        "format": "{}",
        "separate-outputs": true
    },
    "custom/sunset": {
        "format": "🌇 {}",
        "exec": "~/.config/waybar/scripts/sunset",
        "restart-interval": 1
    },
    "tray": {
        // "icon-size": 21,
        "spacing": 10
    },
    "clock": {
        // "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "format": " {:%H:%M (%A) %d %b %Y}",
        // "format": " {:%H:%M}",
        "tooltip-format": " {:%H:%M (%A) %d %b %Y}",
        "on-click": "foot -W 70x35 -H -a floatme -T Calendar cal -y",
        "calendar": {
            // "mode": "year",
            "mode-mon-col": 3,
            "weeks-pos": "right",
            "on-scroll": 1,
            // "on-click-right": "mode",
            "format": {
                "months": "<span color='#ffead3'><b>{}</b></span>",
                "days": "<span color='#ecc6d9'><b>{}</b></span>",
                "weeks": "<span color='#99ffdd'><b>W{}</b></span>",
                "weekdays": "<span color='#ffcc66'><b>{}</b></span>",
                "today": "<span color='#ff6699'><b><u>{}</u></b></span>"
            }
        }
    },
    "pulseaudio": {
        // "scroll-step": 1, // %, can be a float
        "format": "{icon} {volume}%",
        "format-bluetooth": " {icon} {volume}%",
        "format-bluetooth-muted": " ",
        "format-muted": "",
        "format-source": "{volume}% ",
        "format-source-muted": "",
        "format-icons": {
            "default": [
                "",
                ""
            ]
        },
        "on-click": "pavucontrol"
    },
    "custom/notification": {
        "tooltip": false,
        "format": "{icon}",
        "format-icons": {
            "notification": "<span foreground='red'><sup></sup></span>",
            "none": "",
            "dnd-notification": "<span foreground='red'><sup></sup></span>",
            "dnd-none": "",
            "inhibited-notification": "<span foreground='red'><sup></sup></span>",
            "inhibited-none": "",
            "dnd-inhibited-notification": "<span foreground='red'><sup></sup></span>",
            "dnd-inhibited-none": ""
        },
        "return-type": "json",
        "exec-if": "which swaync-client",
        "exec": "swaync-client -swb",
        // sleep is here as workaround for
        // https://github.com/Alexays/Waybar/issues/1968
        "on-click": "sleep 0.1 && swaync-client -t -sw",
        "on-click-right": "swaync-client -d -sw",
        "escape": true
    }
}


```

</details>

<details>
  <summary> waybar/style.css</summary>

```css
* {
  border: none;
  border-radius: 0;
  font-family: Monospace;
  font-size: 14px;
  /* min-height: 24px; */
}

window#waybar {
  background: transparent;
}

window#waybar.hidden {
  opacity: 0.2;
}

/* hide when no window is selected */
/* NOTE: now works only on master, will be in v0.9.19 */
#window.empty {
  background: transparent;
}

/* #window { */
/*   margin-bottom: 8px; */
/*   padding-left: 16px; */
/*   padding-right: 16px; */
/*   border-radius: 26px; */
/*   transition: none; */
/*   background: rgba(27, 22, 22, 0.85); */
/* } */

#workspaces {
  margin-bottom: 4px;
  margin-top: 4px;

  margin-left: 3px;
  border-radius: 26px;
  background: rgba(27, 22, 22, 0.65);
  transition: none;
}

#workspaces button {
  transition: none;
  color: #f8e1e1;
  background: transparent;
  font-size: 16px;
}

#workspaces button.active {
  color: #f8e1e1;
  background: rgba(154, 237, 254, 0.2);
  border-radius: 26px;
}

#workspaces button.urgent {
  color: #f8e1e1;
  background: rgba(154, 237, 254, 1);
  border-radius: 26px;
}

#clock,
#language,
#pulseaudio,
#tray,
#window,
#bluetooth,
#custom-isrecording,
#custom-memory,
#idle_inhibitor,
#cpu,
#custom-cputemp,
#custom-sunset,
#custom-clock,
#custom-notification,
#custom-nvtemp {
  margin-bottom: 4px;
  margin-top: 4px;

  padding-left: 16px;
  padding-right: 16px;
  /* border-radius: 26px; */
  transition: none;
  color: #f8e1e1;
  background: rgba(27, 22, 22, 0.85);
  /* background: rgba(32, 49, 45, 1); */
}

/* borders: (---] */
#idle_inhibitor {
  margin-left: 6px;
  border-radius: 26px 0px 0px 26px;
}

/* borders: [---) */
#custom-notification {
  margin-right: 7px;
  border-radius: 0px 26px 26px 0px;
}

/* Transient (right) */
/* borders: (---) */
#custom-isrecording,
#custom-memory,
#custom-cputemp,
#custom-nvtemp, /* just round things */
#cpu,
#window
{
  margin-left: 7px;
  margin-right: 7px;
  border-radius: 26px;
}

#window {
  font-family: Sans;
  background: rgba(65, 8, 145, 0.45)
}

#bluetooth {
  /* font-family: Monospace; */
  font-size: 12px;
  /* background: rgba(27, 22, 255, 0.65); */
  background: rgba(7, 30, 49, 0.85);
}

#idle_inhibitor.activated {
  color: #bc8b3c;
}

```

</details>
